// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Ptype string `orm:"ptype" json:"ptype"` //
	V0    string `orm:"v0"    json:"v0"`    //
	V1    string `orm:"v1"    json:"v1"`    //
	V2    string `orm:"v2"    json:"v2"`    //
	V3    string `orm:"v3"    json:"v3"`    //
	V4    string `orm:"v4"    json:"v4"`    //
	V5    string `orm:"v5"    json:"v5"`    //
}

// Dogtag is the golang structure for table dogtag.
type Dogtag struct {
	Id         int         `orm:"id,primary"  json:"id"`         //
	PlayerName string      `orm:"player_name" json:"playerName"` //
	KillerName string      `orm:"killer_name" json:"killerName"` //
	Map        string      `orm:"map"         json:"map"`        //
	Weapon     string      `orm:"weapon"      json:"weapon"`     //
	Camp       string      `orm:"camp"        json:"camp"`       //
	Level      int         `orm:"level"       json:"level"`      //
	KillAt     *gtime.Time `orm:"kill_at"     json:"killAt"`     //
	CreateAt   *gtime.Time `orm:"create_at"   json:"createAt"`   //
	UpdateAt   *gtime.Time `orm:"update_at"   json:"updateAt"`   //
	DeleteAt   *gtime.Time `orm:"delete_at"   json:"deleteAt"`   //
}

// User is the golang structure for table user.
type User struct {
	Id       int         `orm:"id,primary"       json:"id"`       // primary id
	Username string      `orm:"username,primary" json:"username"` // username
	Password string      `orm:"password"         json:"password"` // password
	Note     string      `orm:"note"             json:"note"`     //
	NickName string      `orm:"nick_name"        json:"nickName"` // nickName
	Status   int         `orm:"status"           json:"status"`   // 1:enable 2:disable
	CreateAt *gtime.Time `orm:"create_at"        json:"createAt"` //
	UpdateAt *gtime.Time `orm:"update_at"        json:"updateAt"` //
	DeleteAt *gtime.Time `orm:"delete_at"        json:"deleteAt"` //
}

// Weapon is the golang structure for table weapon.
type Weapon struct {
	Id       int         `orm:"id,primary" json:"id"`       //
	FullName string      `orm:"full_name"  json:"fullName"` //
	Name     string      `orm:"name"       json:"name"`     //
	Type     int         `orm:"type"       json:"type"`     // 武器类型 1、手枪 2、冲锋枪 3、投掷物 4、机枪 5、栓动式步枪 6、突击卡宾枪 7、突击步枪 8、精确射手步枪 9、近战武器 10、散弹枪
	Caliber  string      `orm:"caliber"    json:"caliber"`  // 子弹类型
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` //
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` //
	DeleteAt *gtime.Time `orm:"delete_at"  json:"deleteAt"` //
}
