// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"EftServer/app/dao/internal"
)

// dogtagDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type dogtagDao struct {
	*internal.DogtagDao
}

var (
	// Dogtag is globally public accessible object for table dogtag operations.
	Dogtag dogtagDao
)

func init() {
	Dogtag = dogtagDao{
		internal.NewDogtagDao(),
	}
}

// Fill with you ideas below.
