// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"EftServer/app/dao/internal"
)

// weaponDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type weaponDao struct {
	*internal.WeaponDao
}

var (
	// Weapon is globally public accessible object for table weapon operations.
	Weapon weaponDao
)

func init() {
	Weapon = weaponDao{
		internal.NewWeaponDao(),
	}
}

// Fill with you ideas below.
